Repository NVIDIA/k8s-device-plugin, pull requests merged in 2024-04, with the labels that each got.

#611 Revert "Revert nfd 0.15.3 bump"
  deployments/helm/nvidia-device-plugin/Chart.lock
  deployments/helm/nvidia-device-plugin/Chart.yaml
  deployments/helm/nvidia-device-plugin/charts/node-feature-discovery-chart-0.13.0.tgz
  deployments/helm/nvidia-device-plugin/charts/node-feature-discovery-chart-0.15.3.tgz
Labels: dependencies

#622 Add MustGather function to catch logs on E2E failure
  .github/workflows/e2e.yaml
  .gitignore
  go.mod
  go.sum
  tests/e2e/Makefile
  tests/e2e/common/mustgather.go
  tests/e2e/device-plugin_test.go
  tests/e2e/e2e_test.go
  tests/e2e/gpu-feature-discovery_test.go
  vendor/modules.txt
Labels: testing

#566 Migrate GPU feature discovery docs
  README.md
  docs/gpu-feature-discovery/README.md
Labels: documentation

#650 E2E Test: Create a DiagnosticCollector
  tests/e2e/common/diagnostics/collector.go
  tests/e2e/common/diagnostics/extensions.go
  tests/e2e/common/diagnostics/kubernetes.go
  tests/e2e/common/diagnostics/options.go
  tests/e2e/common/mustgather.go
  tests/e2e/device-plugin_test.go
  tests/e2e/e2e_test.go
  tests/e2e/gpu-feature-discovery_test.go
Labels: testing

#677 Enhance e2e logging
  .gitignore
  tests/e2e/Makefile
  tests/e2e/common/kubernetes.go
  tests/e2e/device-plugin_test.go
  tests/e2e/e2e_test.go
  tests/e2e/framework.go
  tests/e2e/framework/expect.go
  tests/e2e/framework/framework.go
  tests/e2e/framework/logs/logging.go
  tests/e2e/framework/test_context.go
  tests/e2e/framework/util.go
  tests/e2e/gomega.go
  tests/e2e/gpu-feature-discovery_test.go
Labels: testing
