Repository NVIDIA/k8s-device-plugin, pull requests merged in 2024-02, with the labels that each got.

#473 Fix: counting server restart times error
  internal/plugin/server.go
Labels: bug

#538 Add actions/stale gh-action
  .github/workflows/stale.yaml
Labels: maintenance

#549 Fix typo on label name at stale action def
  .github/workflows/stale.yaml
Labels: testing

#542 Update golang gh-Action to use go-version-file
  .github/workflows/golang.yaml
Labels: testing

#554 Edit stale message
  .github/workflows/stale.yaml
Labels: maintenance

#557 Increase operations-per-run on stale action
  .github/workflows/stale.yaml
Labels: maintenance

#559 Extract GOLANG_VERSION from versions.mk
  .github/workflows/golang.yaml
  Makefile
  go.mod
  versions.mk
Labels: maintenance, dependencies

#560 clean up replace directives in go.mod
  go.mod
  vendor/modules.txt
Labels: dependencies
